---
pack: service_remediations_pack
ref: service_remediations_pack.deadman_remediations_rule
name: deadman_remediations_rule
enabled: true
trigger:
  type: "core.st2.webhook"
  parameters:
    url: "host_deadman"
criteria:
  trigger.body.message:
    type: exists
    pattern: {}
  "":
    type: "icontains"
    pattern: "critical"
  "":
    type: "icontains"
    pattern: "deadman"
action:
  ref: service_remediations_pack.deadman_remediations_action
  description: Deadman remediations in StackStorm with ssh
  parameters:
    message: "{{ trigger.body.message }}"
