---
pack: remediations_pack
ref: remediations_pack.docker_remediations_rule
description: "NEP@L container remediation rule in StackStorm"
name: docker_remediations_rule
enabled: true
trigger:
  type: "core.st2.webhook"
  parameters:
    url: "dock_remed"
criteria:
  trigger.body.message:
    type: exists
    pattern: {}
  trigger.body.message:
    type: "incontains"
    pattern: "deadman"
  trigger.body.message:
    type: "icontains"
    pattern: "critical"
action:
  ref: remediations_pack.docker_remediations_workflow
  description: Docker remediations in StackStorm with ssh
  parameters:
    message: "{{ trigger.body.message }}"
