---
pack: remediations_pack
ref: remediations_pack.interface_remediations_rule
description: "NEP@L interface remediation rule in StackStorm"
name: interface_remediations_rule
enabled: true
trigger:
  type: "core.st2.webhook"
  parameters:
    url: "interface_remed"
criteria:
  trigger.body.message:
    type: exists
    pattern: {}
  trigger.body.host:
    type: exists
    pattern: {}
action:
  ref: remediations_pack.interface_remediations_action
  description: Interface remediations in StackStorm with ssh
  parameters:
    message: "{{ trigger.body.message }}"
    host: "{{ trigger.body.host }}"
