---
pack: service_remediations_pack
ref: service_remediations_pack.service_remediations_rule
name: service_remediations_rule
enabled: true
trigger:
  type: "core.st2.webhook"
  parameters:
    url: "serv_remed"
criteria:
  trigger.body.message:
    type: exists
    pattern: {}
  "":
    type: "icontains"
    pattern: "critical"
  "":
    type: "incontains"
    pattern: "deadman"
action:
  ref: service_remediations_pack.service_remediations_action
  description: Service remediations in StackStorm with ssh
  parameters:
    message: "{{ trigger.body.message }}"
